### PR TITLE
Updated internal_clients.R to reflect #79 issue

### PR DESCRIPTION
**Pull request by ignaciomsarmiento**
I've fixed get_odata function taking out the extra "/" this fixes the issue pointed on: Error in check_availability() Not Found (HTTP 404). Failed to process request. #79

### CODE REVIEW

**Review by HaEbGIRS — APPROVED** [review]

**Comment by labguyvancouver** [comment]
How do I implement this fix into the package? Sorry, relatively new to R. I just installed the package and am running into the issue that's meant to be resolved by this fix.

**Comment by ignaciomsarmiento** [comment]
> How do I implement this fix into the package? Sorry, relatively new to R. I just installed the package and am running into the issue that's meant to be resolved by this fix.

The fix is already merged. Have you tried installing it directly from GitHub? devtools::install_github("16EAGLE /
getSpatialData")

**Comment by labguyvancouver** [comment]
I did install it directly from GitHub yes. Unfortunately when I run `records<- check_availability(records)`, I get the following error:

Error in .get(paste0(cred[3], "/odata/v1/Products('", x, "')/", field),  : 
  Not Found (HTTP 404). Failed to process request.

I've seen this error elsewhere in the issues list, but am unsure how to fix it.

**Comment by renanbrasil** [comment]
yep, same problem here

> I did install it directly from GitHub yes. Unfortunately when I run `records<- check_availability(records)`, I get the following error:
> 
> Error in .get(paste0(cred[3], "/odata/v1/Products('", x, "')/", field), :
> Not Found (HTTP 404). Failed to process request.
> 
> I've seen this error elsewhere in the issues list, but am unsure how to fix it.

**Comment by 16EAGLE** [comment]
Thanks for your contribution!

**Pull request merged**
